/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-09-28 01:43:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.errors;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.esri.arcgis.server.wa.resource.Messages;
import com.esri.arcgis.server.wa.util.Util;

public final class error_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  String rtl = Messages.getString("wa_displayRightToLeft");
  boolean displayRtl = false;
  if(rtl != null && rtl.length() > 0 && rtl.equalsIgnoreCase("true")) {
	  displayRtl = true;
  }
  String cpath = request.getContextPath();

      out.write('\r');
      out.write('\n');
      out.write(' ');

  if (!displayRtl) {

      out.write("\r\n");
      out.write("\t<html>\r\n");
} else { 
      out.write("\r\n");
      out.write("\t<html DIR=\"RTL\">\r\n");
}
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cpath);
      out.write("/css/webadaptor.css\"/>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"helpHolder\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"configDialog pane\">\r\n");
      out.write("         <div class=\"logoHolder\">\r\n");
      out.write("           <img alt=\"Esri Logo\" class=\"logoImg\" src=\"");
      out.print(cpath );
      out.write("/images/logo.png\" />\r\n");
      out.write("           <h1>ArcGIS Web Adaptor</h1>\r\n");
      out.write("         </div>\r\n");
      out.write("          <div class=\"paneTitleBar\"> </div>\r\n");
      out.write("         <div id=\"contentHolder\" class=\"paneContent\"> \r\n");
      out.write("         \t <div class=\"statusTable\" style=\"background: #FFCDCD; padding-top: 5px; margin-top: 14px\"> \r\n");
      out.write("                      <table>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td width=\"50\">\r\n");
      out.write("                            <img alt=\"\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/error.png\" />\r\n");
      out.write("                          </td>\r\n");
      out.write("                          <td>\r\n");
      out.write("                      <p class=\"errorLabel\">\r\n");
      out.write("                         ");
      out.print( 
                              request.getAttribute("javax.servlet.error.message")
                            );
      out.write("\r\n");
      out.write("               \t\t</p>\r\n");
      out.write("                          </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                      </table>\r\n");
      out.write("                 </div>\r\n");
      out.write("         </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
