/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-09-28 01:42:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.esri.arcgis.server.wa.constants.WebAdaptorConstants;
import java.util.Date;
import com.esri.arcgis.server.wa.util.Util;
import com.esri.arcgis.server.wa.util.ServerUtil;
import com.esri.arcgis.server.wa.resource.Messages;
import java.util.Locale;

public final class ServerWebAdaptor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  String cpath = request.getContextPath();
  String rpath = Util.getAppURL(request);
  String siteURL = (String) request.getAttribute(WebAdaptorConstants.SITE_URL_PROP);
  siteURL = siteURL != null ? siteURL : "";
  siteURL = Util.encodeHtml(siteURL);
  String hosts = (String) request.getAttribute(WebAdaptorConstants.SERVER_NODES_PROP);
  hosts = hosts != null ? hosts : "";
  String updateTimeStamp = (String) request.getAttribute(WebAdaptorConstants.UPDATE_TIME_STAMP_PROP);
  updateTimeStamp = updateTimeStamp != null ? new Date(Long.parseLong(updateTimeStamp)).toString() : "";
  String updatedServerList = (String) request.getAttribute(WebAdaptorConstants.UPDATED_SERVER_LIST);
  boolean serverListUpdated = updatedServerList != null ? Boolean.parseBoolean(updatedServerList) : true;
  String enableAdmin = (String) request.getAttribute(WebAdaptorConstants.ENABLE_ADMIN_ACCESS_PROP);
  boolean enableAdminAccess = enableAdmin != null ? Boolean.parseBoolean(enableAdmin) : false;
  String publicKey = (String)request.getAttribute("PUBLIC_KEY");
  String modulus = (String)request.getAttribute("MODULUS");
  String rtl = Messages.getString("wa_displayRightToLeft");
  boolean displayRtl = false;
  if(rtl != null && rtl.length() > 0 && rtl.equalsIgnoreCase("true")) {
	  displayRtl = true;
  }
  String helpLink = ServerUtil.getServerConfigHelpLink(config);
  String url = Util.getAppURL(request);

      out.write('\r');
      out.write('\n');
      out.write(' ');

  if (!displayRtl) {

      out.write("\r\n");
      out.write("\t<html>\r\n");

  } else {

      out.write("\r\n");
      out.write("\t<html DIR=\"RTL\">\r\n");

  }

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cpath);
      out.write("/css/webadaptor.css\"/>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.print(rpath );
      out.write("/js/BigInt.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.print(rpath );
      out.write("/js/Barrett.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.print(rpath );
      out.write("/js/RSA.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.print(rpath );
      out.write("/js/admin.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  \tfunction setProperties() {\r\n");
      out.write("  \t\tdocument.getElementById('goback').value = \"\";\r\n");
      out.write("  \t}\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"setProperties();\">\r\n");
      out.write(" \r\n");
      out.write("   <div class=\"helpHolder\">\r\n");
      out.write("      <p id=\"helpLinkElement\" class=\"help\" align=\"right\">\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.print(helpLink);
      out.write("\" target=\"blank\">");
      out.print(Messages.getString("help"));
      out.write("</a>\r\n");
      out.write("        <span> | </span>\r\n");
      out.write("        <a href=\"#\" class=\"tooltip about\" id=\"confighelpt1\" tabindex=\"-1\">About\r\n");
      out.write("            <span style=\"width:auto;text-align:justify;\">\r\n");
      out.write("              <label ID=\"waInfo1\">");
      out.print(Util.getWAInfo() );
      out.write("</label>\r\n");
      out.write("                <br />\r\n");
      out.write("              <label ID=\"waInfo2\">");
      out.print(Util.getVersionInfo() );
      out.write("</label>\r\n");
      out.write("            </span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("   <div class=\"configDialog pane\">\r\n");
      out.write("      <div class=\"logoHolder\">\r\n");
      out.write("        <img alt=\"Esri Logo\" class=\"logoImg\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/logo.png\" />\r\n");
      out.write("        <h1>ArcGIS Web Adaptor</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"paneTitleBar\"></div>\r\n");
      out.write("      <div id=\"contentHolder\" class=\"paneContent\">\r\n");
      out.write("        <p class=\"center\">\r\n");
      out.write("          <label class=\"style1\">");
      out.print(Messages.getString("webserverconnecton"));
      out.write("</label>\r\n");
      out.write("        </p>\r\n");
      out.write("        <form name=\"serverWebadaptorConfig\" method=\"POST\" action=\"");
      out.print(cpath);
      out.write("/webadaptor/server\" onsubmit=\"return encryptFormData('");
      out.print( publicKey);
      out.write("','','");
      out.print(modulus);
      out.write("');\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <table id=\"tableConfig\" class=\"configTable\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td style=\"width: 250px\">\r\n");
      out.write("                  <label>");
      out.print(Messages.getString("gisserverurl"));
      out.write(": </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                  <input type=\"text\" size=\"120\" id=\"SiteURLUi\" value=\"");
      out.print(siteURL);
      out.write("\" style=\"width: 250px;\"/>\r\n");
      out.write("                <!-- </td>\r\n");
      out.write("                <td> -->\r\n");
      out.write("                  <a href=\"#\" class=\"tooltip\" id=\"confighelpt1\" tabindex=\"-1\">?\r\n");
      out.write("                    <span>\r\n");
      out.write("                      <label>");
      out.print(Messages.getString("gisserverurltooltip"));
      out.write("</label>\r\n");
      out.write("                    </span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td class=\"runAtExample\">\r\n");
      out.write("                  <label>");
      out.print(Messages.getString("urlexample"));
      out.write("</label>\r\n");
      out.write("                </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                  <label>");
      out.print(Messages.getString("username"));
      out.write(": </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                  <input type=\"text\" size=\"120\" id=\"UserNameUi\" style=\"width: 250px\" />                  \r\n");
      out.write("                <!-- </td>\r\n");
      out.write("                <td> -->\r\n");
      out.write("                  <a href=\"#\" class=\"tooltip\" id=\"confighelpt12\" tabindex=\"-1\">?\r\n");
      out.write("                    <span>\r\n");
      out.write("                      ");
      out.print(Messages.getString("usernametooltip"));
      out.print(Messages.getString("usernametooltip1"));
      out.write("\r\n");
      out.write("                    </span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                  <label>");
      out.print(Messages.getString("password"));
      out.write(": </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                \t<input type=\"password\" size=\"120\" name=\"Password\" style=\"width: 250px\"  autocomplete=”off”/>\r\n");
      out.write("                <!-- </td>\r\n");
      out.write("                <td> -->\r\n");
      out.write("                  <a href=\"#\" class=\"tooltip\" id=\"confighelpt3\" tabindex=\"-1\">?\r\n");
      out.write("                    <span>\r\n");
      out.write("                      ");
      out.print(Messages.getString("passwordtooltip"));
      out.write("\r\n");
      out.write("                    </span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td colspan=\"2\" class=\"enableAdminAccessHolder\">                  \r\n");
      out.write("                  <input type=\"checkbox\" id=\"enableAdminAccessUi\" value=\"");
      out.print(enableAdminAccess ? true : false);
      out.write('"');
      out.write(' ');
      out.print(Util.checked(enableAdminAccess));
      out.write(" >\r\n");
      out.write("                  <label for=\"enableAdminAccessUi\">");
      out.print(Messages.getString("enableadminaccess"));
      out.write("</label>\r\n");
      out.write("                  <a href=\"#\" class=\"tooltip\" id=\"confighelpt5\" tabindex=\"-1\">?\r\n");
      out.write("\t                  <span>                \t\r\n");
      out.write("\t\t\t  \t\t\t");
      out.print(Messages.getString("enableadminaccesstooltip"));
      out.write(":\r\n");
      out.write("\t\t\t  \t\t\t<br/><br/>\r\n");
      out.write("\t                  \t<label>");
      out.print(Messages.getString("enableadminaccesstooltip1"));
      out.write(": </label>\r\n");
      out.write("\t\t\t  \t\t\t<br/>");
      out.print(Messages.getString("enableadminaccesstooltip2"));
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t<br/></br>\r\n");
      out.write("\t                  \t<label> ");
      out.print(Messages.getString("enableadminaccesstooltip3"));
      out.write(": </label>\r\n");
      out.write("\t\t\t  \t\t\t<br/>");
      out.print(Messages.getString("enableadminaccesstooltip4"));
      out.write("                \r\n");
      out.write("\t                  </span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td id=\"tableCellSubmitButton\"></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td colspan=\"2\">\r\n");
      out.write("                  <div class=\"statusTable\">\r\n");
      out.write("                    <table>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td width=\"40\">\r\n");
      out.write("                          <img alt=\"\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/info.png\" />\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("\t\t\t\t\t\t    ");

							  if (hosts != null && hosts.length() > 0) {
							    String[] hList = hosts.split(",");
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<label> ");
      out.print(Messages.getString("gisserverstatus"));
      out.write(" </label>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"nodeList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									  for (String h : hList) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \t<label><li>");
      out.print(h);
      out.write("</li></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									  }
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>");
      out.print(Messages.getMessage("gisserverstatus2", updateTimeStamp));
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>&nbsp;</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>");
      out.print(Messages.getString("srvcdirurl"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.print(cpath);
      out.write("/rest/services\" target=\"blank\">");
      out.print(url);
      out.write("/rest/services</a>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>");
      out.print(Messages.getString("srvcdirurl2"));
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								  } else {
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(Messages.getString("nomachinesstatus"));
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								  }
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t                        </td>\r\n");
      out.write("\t                      </tr>\r\n");
      out.write("\t                    </table>\r\n");
      out.write("                  \t\t");

						  if (hosts != null && hosts.length() > 0) {
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div style=\"clear:both\"></div>\r\n");
      out.write("          <input type=\"submit\" value=\"");
      out.print(Messages.getString("configure"));
      out.write("\" />\r\n");
      out.write("    \t    <input type=\"button\" onclick=\"document.getElementById('goback').value='true';document.forms[0].submit();\" value=\"");
      out.print(Messages.getString("wa_config_back"));
      out.write("\"/>\r\n");
      out.write("\t\t  \t  \r\n");
      out.write("\t\t  \t<input type=\"hidden\" name=\"SiteURL\" id=\"SiteURL\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"UserName\" id=\"UserName\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"goback\" id=\"goback\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"enableAdminAccess\" id=\"enableAdminAccess\"/>\r\n");
      out.write("        </form>\r\n");
      out.write("        <div style=\"clear:both\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
