/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-09-28 01:42:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.esri.arcgis.server.wa.constants.WebAdaptorConstants;
import java.util.Date;
import com.esri.arcgis.server.wa.util.Util;
import com.esri.arcgis.server.wa.util.PortalUtil;
import com.esri.arcgis.server.wa.resource.Messages;
import java.util.Locale;

public final class WebAdaptor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  String cpath = request.getContextPath();
  String rpath = Util.getAppURL(request);
  String rtl = Messages.getString("wa_displayRightToLeft");
  boolean displayRtl = false;
  if(rtl != null && rtl.length() > 0 && rtl.equalsIgnoreCase("true")) {
	  displayRtl = true;
  }
  String helpLink = Util.getHelpLink(config);
  boolean serverChecked = true;
  
  String portalInstallHelpLink = PortalUtil.getPortalInstallHelpLink(config);
  String portalSSLConfigHelpLink = PortalUtil.getPortalSSLConfigHelpLink(config);
  
  String selectionVal = Util.getParamIgnoreCase("wa_config", request, null, false);
  if(!Util.isEmpty(selectionVal) && selectionVal.equals("portal"))
    serverChecked = false;        
  
  String portalConfiguredStr = Util.getRequestAttribute(request, "PortalConfigured");
  boolean portalConfigured =  Util.isEmpty(portalConfiguredStr) ? false : Boolean.valueOf(portalConfiguredStr) ;
  
  String portalConfiguredHttpStr = Util.getRequestAttribute(request, "PortalConfiguredHttp");
  boolean portalConfiguredHttp =  Util.isEmpty(portalConfiguredHttpStr) ? false : Boolean.valueOf(portalConfiguredHttpStr) ;
  
  String portalConfiguredHttpsStr = Util.getRequestAttribute(request, "PortalConfiguredHttps");
  boolean portalConfiguredHttps = Util.isEmpty(portalConfiguredHttpsStr)? false : Boolean.valueOf(portalConfiguredHttpsStr) ;
  
  String portalConfiguredHttps444Str = Util.getRequestAttribute(request, "PortalConfiguredHttps443");
  boolean portalConfiguredHttps443 = Util.isEmpty(portalConfiguredHttps444Str)? false : Boolean.valueOf(portalConfiguredHttps444Str) ;

  String waConfig = Util.getParamIgnoreCase("wa_config", request);
  if(Util.isEmpty(waConfig)) {
    waConfig = "server";
  }
  
  String serverNodes = Util.getRequestAttribute(request, WebAdaptorConstants.SERVER_NODES_PROP);
  
  String portalNodes = Util.getRequestAttribute(request, WebAdaptorConstants.PORTAL_NODES);

      out.write('\r');
      out.write('\n');
      out.write(' ');

  if (!displayRtl) {

      out.write("\r\n");
      out.write("\t<html>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");

  } else {

      out.write("\r\n");
      out.write("\t<html DIR=\"RTL\">\r\n");

  }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cpath);
      out.write("/css/webadaptor.css\"/>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tfunction setErrorTexts() {\r\n");
      out.write("\t    var portalConfigured = \"");
      out.print(portalConfiguredStr);
      out.write("\";           \r\n");
      out.write("\t    var portalOptions = \"");
      out.print(waConfig);
      out.write("\";\r\n");
      out.write("\t    var serverSel = document.getElementById('radio_Server');\r\n");
      out.write("\t    var portalSel = document.getElementById('radio_Portal');\r\n");
      out.write("\t    if(document.getElementById('statusTable') != null)\r\n");
      out.write("\t    \tdocument.getElementById('statusTable').style.display=\"none\";\r\n");
      out.write("\t    if(portalOptions == \"server\") {\r\n");
      out.write("\t        serverSel.checked = true;\r\n");
      out.write("\t    } else if(portalOptions == \"portal\") {\r\n");
      out.write("\t        portalSel.checked = true;\r\n");
      out.write("\t        if(portalConfigured != null && portalConfigured != \"true\") {\r\n");
      out.write("\t             document.getElementById('statusTable').style.display=\"block\";\r\n");
      out.write("\t        }\r\n");
      out.write("\t    } else {\r\n");
      out.write("\t    \tserverSel.checked = true;\r\n");
      out.write("\t    \tportalOptions.value = \"server\";\r\n");
      out.write("\t    }\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t function setPortalOptions(portalOption) {\r\n");
      out.write("\t\tif(document.getElementById('statusTable') != null)\r\n");
      out.write("\t    \tdocument.getElementById('statusTable').style.display=\"none\";\r\n");
      out.write("\t    var portalConfigured = \"");
      out.print(portalConfiguredStr);
      out.write("\"; \r\n");
      out.write("\t    if(portalOption.checked) {\r\n");
      out.write("\t      if(portalConfigured != null && portalConfigured == \"false\")\r\n");
      out.write("\t\t     document.getElementById('statusTable').style.display=\"block\";\r\n");
      out.write("\t    }\r\n");
      out.write("\t  }\r\n");
      out.write("\t     \r\n");
      out.write("\t  function setServerOptions(serverOption) {\r\n");
      out.write("\t    if(serverOption.checked) {\r\n");
      out.write("\t        document.getElementById('statusTable').style.display=\"none\";\r\n");
      out.write("\t    }\r\n");
      out.write("\t  }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"setErrorTexts();\">\r\n");
      out.write("\r\n");
      out.write("   <div class=\"helpHolder\">\r\n");
      out.write("      <p id=\"helpLinkElement\" class=\"help\" align=\"right\">\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.print(helpLink);
      out.write("\" target=\"blank\">");
      out.print(Messages.getString("help"));
      out.write("</a>\r\n");
      out.write("        <span> | </span>\r\n");
      out.write("        <a href=\"#\" class=\"tooltip about\" id=\"confighelpt1\" tabindex=\"-1\">About\r\n");
      out.write("            <span style=\"width:auto;text-align:justify;\">\r\n");
      out.write("              <label ID=\"waInfo1\">");
      out.print(Util.getWAInfo() );
      out.write("</label>\r\n");
      out.write("                <br />\r\n");
      out.write("              <label ID=\"waInfo2\">");
      out.print(Util.getVersionInfo() );
      out.write("</label>\r\n");
      out.write("            </span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("     <div class=\"configDialog pane\">\r\n");
      out.write("      <div class=\"logoHolder\">\r\n");
      out.write("        <img alt=\"Esri Logo\" class=\"logoImg\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/logo.png\" />\r\n");
      out.write("        <h1>ArcGIS Web Adaptor</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"paneTitleBar\"></div>\r\n");
      out.write("      \r\n");
      out.write("      <div id=\"contentHolder\" class=\"paneContent\">\r\n");
      out.write("        <p class=\"center\">\r\n");
      out.write("          <label class=\"style1\">");
      out.print(Messages.getString("wa_config_server_or_portal"));
      out.write("</label>\r\n");
      out.write("        </p>\r\n");
      out.write("        \r\n");
      out.write("\t  \t   <form name=\"webadaptorConfig\" method=\"POST\" action=\"");
      out.print(cpath);
      out.write("/webadaptor\">\r\n");
      out.write("\t  \t\t<div>\r\n");
      out.write("\t          <table id=\"waTableConfig\" runat=\"server\" class=\"configTable\">\r\n");
      out.write("\t        \t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"radioHolder\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" onclick=\"setServerOptions(this);\" id=\"radio_Server\" ");
      out.print(serverChecked ? "checked" : "" );
      out.write(" name=\"wa_config\" value=\"server\"/>\r\n");
      out.write("\t\t\t\t\t\t<label>");
      out.print(Messages.getString("wa_config_server"));
      out.write(" </label>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"radioHolder\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" size=\"120\" onclick=\"setPortalOptions(this);\" id=\"radio_Portal\" ");
      out.print(!serverChecked ? "checked" : "" );
      out.write(" name=\"wa_config\" value=\"portal\"/>\r\n");
      out.write("\t\t\t\t\t\t<label>");
      out.print(Messages.getString("wa_config_portal"));
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t       <td id=\"tableCellSubmitButton\">\r\n");
      out.write("\t\t\t       </td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t            <td colspan=\"2\">\r\n");
      out.write("\t               <div id=\"statusTable\" class=\"statusTable\" style=\"background: #ffffcb\">\r\n");
      out.write("\t                  <table>\r\n");
      out.write("\t                     <tr>\r\n");
      out.write("\t                    \t   <td width=\"50\">\r\n");
      out.write("\t                        \t<img alt=\"\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/warning.png\" />\r\n");
      out.write("\t                        </td>\r\n");
      out.write("\t                        <td>\r\n");
      out.write("\t\t\t                   ");
 if (!portalConfigured && !portalConfiguredHttp) {	    
			                   
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div  class=\"HighLightText\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label> ");
      out.print(Messages.getString("wa_portal_prerequisite"));
      out.write(" </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ErrorText\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label> ");
      out.print(Messages.getString("wa_portal_prereq_desc1"));
      out.write(" </label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label> ");
      out.print(Messages.getString("wa_portal_prereq_desc2"));
      out.write(" </label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.print(portalInstallHelpLink);
      out.write("\" target=\"blank\">");
      out.print(Messages.getString("wa_portal_prereq_desc3"));
      out.write("</label></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 
										} else if(!portalConfigured && !portalConfiguredHttps) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div  class=\"HighLightText\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label> ");
      out.print(Messages.getString("wa_portal_prerequisite"));
      out.write(" </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ErrorText\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label> ");
      out.print(Messages.getString("wa_portal_prereq_nohtps_desc1"));
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.print(portalSSLConfigHelpLink);
      out.write("\" target=\"blank\">");
      out.print(Messages.getString("wa_portal_prereq_nohtps_desc2"));
      out.write("</label></a>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 
										} else if(!portalConfigured && portalConfiguredHttps && !portalConfiguredHttps443) {
									
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div  class=\"HighLightText\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label> ");
      out.print(Messages.getString("wa_portal_prerequisite"));
      out.write(" </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ErrorText\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label> ");
      out.print(Messages.getString("wa_portal_prereq_nohtps443_desc1"));
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.print(portalSSLConfigHelpLink);
      out.write("\" target=\"blank\">");
      out.print(Messages.getString("wa_portal_prereq_nohtps_desc2"));
      out.write("</label></a>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 
										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t   </td>\r\n");
      out.write("\t                  </tr>\r\n");
      out.write("\t                 </table>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t               </td>\r\n");
      out.write("\t             </tr>\r\n");
      out.write("\t             <tr></tr>\r\n");
      out.write("\t              <tr>\r\n");
      out.write("\t                <td colspan=\"2\">\r\n");
      out.write("\t                    <div id=\"Div2\" class=\"statusTable\">\r\n");
      out.write("\t                      <table>\r\n");
      out.write("\t                        <tr>\r\n");
      out.write("\t                          <td width=\"50\">\r\n");
      out.write("\t                            <img alt=\"\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/info.png\" />\r\n");
      out.write("\t                          </td>\r\n");
      out.write("\t                          <td>\r\n");
      out.write("\t                            <div id=\"Div5\" class=\"ErrorText\">\r\n");
      out.write("\t                                ");

								               if (serverNodes != null && serverNodes.length() > 0) {
								            
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t                  <label class=\"statusText\">");
      out.print(Messages.getString("ags_configured_status"));
      out.write("</Label>\r\n");
      out.write("\t\t\t\t\t\t\t\t            ");

								               } else {
								            
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t                  <label class=\"statusText\">");
      out.print(Messages.getString("ags_not_configured_status"));
      out.write("</Label>\r\n");
      out.write("\t\t\t\t\t\t\t\t            ");

								               }
								            
      out.write("\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <br />\r\n");
      out.write("\t                            <div id=\"Div3\" class=\"ErrorText\">\r\n");
      out.write("\t                              ");

							               if (portalNodes != null && portalNodes.length() > 0) {
							            
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t                  <label class=\"statusText\">");
      out.print(Messages.getString("portal_configured_status"));
      out.write("</Label>\r\n");
      out.write("\t\t\t\t\t\t\t            ");

							               } else {
							            
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t                  <label class=\"statusText\">");
      out.print(Messages.getString("portal_not_configured_status"));
      out.write("</Label>\r\n");
      out.write("\t\t\t\t\t\t\t            ");

							               }
							            
      out.write("\r\n");
      out.write("\t                            </div>    \r\n");
      out.write("\t                          </td>\r\n");
      out.write("\t                        </tr>\r\n");
      out.write("\t                      </table>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                  </td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t              </table>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div style=\"clear:both\"></div>\r\n");
      out.write("\t            <input type=\"submit\" style=\"margin-left:200px\" value=\"");
      out.print(Messages.getString("wa_config_next"));
      out.write("\" />\r\n");
      out.write("\t          </form>\r\n");
      out.write("\t        <div style=\"clear:both\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
